### ISSUE TITLE
Problems with Links in Readme file

### ISSUE THREAD

**Issue by cameronrainey** [Ford/AVData#1]
Hi,

There are some issues with some of the links in the README. The link: https://github.com/Ford/AVData/blob/master/avdata.ford.com/Download Gives a 404 error when clicked.

The same with https://github.com/Ford/AVData/blob/master/avdata.ford.com

I believe these are not supposed to have the https://github.com/Ford/AVData/blob/master prepended.

Even so, going directly to avdata.ford.com/Download, a login is required to proceed, with no clear way to register.

**Comment by ankitvora7** [comment]
Hi @cameronrainey - we fixed the broken links and the website is live now. Thanks for pointing this out.
