### ISSUE TITLE
Converting ground truth poses(location) into WGS84 frame

### ISSUE THREAD

**Issue by ZiminXia** [Ford/AVData#12]
Hi,

Thank you for your work!
Do you provide any code for converting the ground truth pose(location) from the local frame into WGS84 (GPS) coordinate frame?

**Comment by agarwalsid** [comment]
@ZXia221, the origin is located at 42.294319, -83.223275 (Lat, Long). The map and poses are with respect to this origin. You can use this information to transform all poses into GPS coordinate frame.

**Comment by ZiminXia** [comment]
@agarwalsid, yes, you are right. 
From WGS84 to the local frame, I guess that the (lat, long) is first converted to (Northing, Easting) in the UTM frame. Using the origin, I can calculate the translation between UTM and the local frame. But, is there any rotation between these two coordinate frames? If not, which axis (x or y) in the local frame is aligned with the Northing?

**Comment by ZiminXia** [comment]
A follow-up question: how did you linearize the WGS84 frame? I tried to flatten the oblate spheroid into the UTM frame, then apply the translation on it to get local coordinates. But the difference between the resulting trajectory and the given trajectory (raw pose and GT pose) reaches several hundred meters.

**Comment by ankitvora7** [comment]
@ZXia221 In terms of the rotation, the map frame is NED (North,East,Down) whereas the UTM is ENU (East, North,Up) so you'll have to apply a transformation there. 
In terms of the difference between raw pose and GT pose, you should expect some differences since the raw pose drifts. Can you do the same analysis with localized pose ? Also can you share a plot/image ?

**Comment by ZiminXia** [comment]
Sorry, I think my statement was unclear.
I converted the origin 42.294319, -83.223275 (Lat, Long) into UTM (Northing, Easting) to get the origin in UTM.
After this, in order to get the GPS trajectory in the local frame, all the GPS measurements (Lat, Long) are transformed into UTM (Northing, Easting) and subtracted by the origin in UTM (Northing, Easting).
The difference between this resulting trajectory (local GPS trajectory) and raw pose is large. 

When you linearize the WGS84 oblate spheroid, which global frame do you use? In other words, what is 'll2xy()' function in the figure below. Does ll2xy mean WGS84 to UTM?

<img width="636" alt="image" src="https://user-images.githubusercontent.com/58000787/80143532-8859a900-85df-11ea-8fc8-fd6481898478.png">

**Comment by ankitvora7** [comment]
@ZXia221 apologies for the confusion. If you look at section 7.5 of this document (https://portal.opengeospatial.org/files/16-011r4) it talks about converting angular displacements in WGS84 to linear displacements in X and Y. It uses the dlat and dlon (which is nothing but the difference between lat,lon of any point and the lat, lon at the origin point) and converts it to X and Y.

**Comment by ZiminXia** [comment]
Problem solved. 
Thanks a lot!

**Comment by juliajing72** [comment]
> Sorry, I think my statement was unclear.
> I converted the origin 42.294319, -83.223275 (Lat, Long) into UTM (Northing, Easting) to get the origin in UTM.
> After this, in order to get the GPS trajectory in the local frame, all the GPS measurements (Lat, Long) are transformed into UTM (Northing, Easting) and subtracted by the origin in UTM (Northing, Easting).
> The difference between this resulting trajectory (local GPS trajectory) and raw pose is large.
> 
> When you linearize the WGS84 oblate spheroid, which global frame do you use? In other words, what is 'll2xy()' function in the figure below. Does ll2xy mean WGS84 to UTM?
> 
> <img alt="image" width="636" src="https://user-images.githubusercontent.com/58000787/80143532-8859a900-85df-11ea-8fc8-fd6481898478.png">

Hi, sorry, but I was wondering how you managed to solve the problem of reducing the difference between the converted GPS coordinates and the pose coordinates? 
thank you
