### ISSUE TITLE
About the linear accelaration

### ISSUE THREAD

**Issue by Saixiaoma** [Ford/AVData#13]
Hi，dear authors,
I have read your paper and your websites about this AVData. I have the question about the linear accelartion. and I know it has removed the gravity and represents the oriention of body frame in the vehicle.
The imu.csv is transformed by your providing scripts. But the linear accelartion is so big like  this and i can't understand the reason.
![v2_log5_accelaration_part](https://user-images.githubusercontent.com/45616513/80297904-299c5700-87ba-11ea-883f-2b075c5de984.png)

I really hope you can give me a reply . 
Thank you so much

**Comment by Saixiaoma** [comment]
![v2_log5_accelaration_part](https://user-images.githubusercontent.com/45616513/80297920-4173db00-87ba-11ea-8d7d-003533ef26f5.png)

**Comment by ankitvora7** [comment]
Hi @Saixiaoma , can you tell us which log and time interval does this data snapshot belong to so that we can look on our end? Usually, you can expect spikes in imu data since it is subject to a lot of noise including the vibrations of the vehicle. You can remove this noise by using a low pass filter/moving-average filter or a KF

**Comment by huanhexiao** [comment]
Hi guys, mine by contrast is so small,  will u please explain this for me?
![acc](https://user-images.githubusercontent.com/12584242/99872359-44359200-2c1c-11eb-9891-37a3c6ed99b5.png)

**Comment by impce-lg** [comment]
Hi guys, mine by contrast is so small. I wonder whether the gravity has been removed according to  @Saixiaoma , but i'm not sure about this. All i want to know is whether i obtain a correct result. 
Besides,  most INS algorithms such as GPS/INS integration remove gravity inside the program, so i don't know how to deal with such a preprocessed dataset. 
Would u please do me a favor?Thanks in advance!
![acc](https://user-images.githubusercontent.com/12584242/99872382-6202f700-2c1c-11eb-9d6d-31a3b291d0e3.png)
