### ISSUE TITLE
Direct access Rosbags on S3

### ISSUE THREAD

**Issue by wiegelmann** [Ford/AVData#14]
Is it possible to put the Rosbags in a non-zipped form on S3, just the .bag files?

We have a bunch of analytics tools that can parse and read Rosbags directly on S3 w/o copying and converting. Makes sense if you process petabytes of bags per day, exploring the data and searching for edge cases.

Many thanks for your release of public AV data! That helps a lot.

**Comment by ankitvora7** [comment]
Hi @wiegelmann, the rosbags were zipped so that it is easier/quicker for us to upload and users to download. Let us internally discuss and get back to you on the feasibility of uploading direct rosbags.

**Comment by wiegelmann** [comment]
@ankitvora7 Any updates on your internal discussions?

Is the data released under MIT license, too?
