### ISSUE TITLE
Online LiDAR scans in sensor frame or body frame?

### ISSUE THREAD

**Issue by troiwill** [Ford/AVData#18]
Hello. I extracted LiDAR scans from the ROS bag with the help of **multi_lidar_convert.launch**. However, I am not sure which coordinate frame the LiDAR point clouds are in when they are published by multi_lidar_convert.launch. Are the published point clouds in the respective LiDAR frames or in the body frame?

**Comment by troiwill** [comment]
I found an answer to my question via the link (https://avdata.ford.com/data/default.aspx) under section **Coordinate Frames**. The section mentions that sensor data is recorded in the sensor frame and must be transformed into the body frame. So, for example, if I want to transform points from any LiDAR to world frame, I need to apply the following transform:

**point_in_world_frame**   =   **world_to_body_transform**   *   **body_to_lidar_transform**   *   **point_in_lidar_frame**

Is this correct?

**Comment by ankitvora7** [comment]
@troiwill You are almost there! the transformations should be flipped -  

point_in_world_frame = body_to_world_transform * lidar_to_body_transform * point_in_lidar_frame

**Comment by troiwill** [comment]
> point_in_world_frame = body_to_world_transform * lidar_to_body_transform * point_in_lidar_frame

@ankitvora7, thanks for the correction! 😄 Much appreciated.
