### ISSUE TITLE
Labeled Data for Seasonal Variation or Scenarios?

### ISSUE THREAD

**Issue by kevinsoucy** [Ford/AVData#19]
Hi, Does the Ford AV dataset contain any labels for seasonal variation (ie sunny, cloudy, snow) or driving scenarios (ie freeway, overpass, residential)? If so, where would I be able to find this information in the Sample Data?

**Comment by ankitvora7** [comment]
@kevinsoucy The information you are looking for is in the download section of the website. Each log has a list of tags associated with it (as shown in the image). The Sample Data is from log 3.

![tags](https://user-images.githubusercontent.com/9420343/86537571-f4993880-bebd-11ea-8656-627b487abe43.png)
