### ISSUE TITLE
IMU to GPS antenna lever arm

### ISSUE THREAD

**Issue by juliajing72** [Ford/AVData#20]
Hi

Thank you for sharing the data and your work! I was wondering if you could also share the lever arm calibration between the GPS antenna and the IMU frame, or with respect to the vehicle body frame? 
thank you!

**Comment by impce-lg** [comment]
> Hi
> 
> Thank you for sharing the data and your work! I was wondering if you could also share the lever arm calibration between the GPS antenna and the IMU frame, or with respect to the vehicle body frame?
> thank you!

I think it is zero, since the imu measurements and GPS BLH are both under body frame

**Comment by juliajing72** [comment]
> > Hi
> > Thank you for sharing the data and your work! I was wondering if you could also share the lever arm calibration between the GPS antenna and the IMU frame, or with respect to the vehicle body frame?
> > thank you!
> 
> I think it is zero, since the imu measurements and GPS BLH are both under body frame

Thanks, do you mean the GPS position outputs are already offset to the vehicle frame location, not the antenna location?

**Comment by impce-lg** [comment]
> > > Hi
> > > Thank you for sharing the data and your work! I was wondering if you could also share the lever arm calibration between the GPS antenna and the IMU frame, or with respect to the vehicle body frame?
> > > thank you!
> > 
> > 
> > I think it is zero, since the imu measurements and GPS BLH are both under body frame
> 
> Thanks, do you mean the GPS position outputs are already offset to the vehicle frame location, not the antenna location?

Yeah, i mean that. Generally speaking, GNSS/INS fusion should transform the result to IMU origin.
