### ISSUE TITLE
[Question] integrate images and laser scans.

### ISSUE THREAD

**Issue by femust** [Ford/AVData#24]
Hey, do you have some smart method to integrate lidar scans and images since as I saw the images are not synchronized explicitly with rosbag time steps, therefore some 'approximations' should be done, and I wonder whether it was your plan from the beginning in this dataset or you addressed somehow this issue? I am asking since I would like to avoid a method that I have a time step from rosbag and I look for the corresponding image-string that's "close".

Best

**Comment by ankitvora7** [comment]
Hi @femust - You're right! The most obvious way to deal with this is to choose a camera image for each lidar scan (since lidar runs at a lower frequency than cameras). You can do this using the nearest neighbor approach. Also have a threshold for the difference between timestamps so that you're not using too old information.

**Comment by femust** [comment]
Ok thanks for the info :)

**Comment by femust** [comment]
![image](https://user-images.githubusercontent.com/26916586/103558962-b7862100-4eb5-11eb-895a-70fb5fa4e804.png)
Nah, I think that there is in general problem in rosbag with synchronization of lidar scans, since there is like a constant spatial offset between scans
![image](https://user-images.githubusercontent.com/26916586/103559262-23688980-4eb6-11eb-9913-ade21f8ba1db.png)

**Comment by ankitvora7** [comment]
@femust The lidar scans do not start at the exact same position and time. Moreover, these scans are not motion compensated. So each lidar will have different levels of effect of both the causes I mentioned.
