### ISSUE TITLE
IMU - gravity removed from linear accel?

### ISSUE THREAD

**Issue by kylelindgren** [Ford/AVData#3]
To confirm, has gravity already been removed from the linear acceleration component of the IMU data in the rosbags?

**Comment by ankitvora7** [comment]
Hi @kylelindgren yes it is the gravity compensated acceleration.

**Comment by kylelindgren** [comment]
Excellent, thank you!

**Comment by slamhuangxin** [comment]
is there the imu data which doesn't remove the gravity from the linear acceleration?

**Comment by slamhuangxin** [comment]
Hello, @kylelindgren  Do you know or find why the linear acceleration is so large, especially the z-axis direction, some almost 6g? thanks

**Comment by slamhuangxin** [comment]
Hello, @kylelindgren Do you know or find why the linear acceleration is so large, especially the z-axis direction, some almost 6m/s^2? thanks

**Comment by Saixiaoma** [comment]
@slamhuangxin @kylelindgren ,hi, i meet the same question, if you get a right answer. I hope you can give me a reply. Thank you so much

**Comment by kylelindgren** [comment]
I have not been working with this dataset recently and unfortunately am unable to answer this question. You may want to open another issue for greater exposure.

**Comment by impce-lg** [comment]
@ankitvora7 @kylelindgren hi guys, do u mean i can simply add gravity 9.8m/s^2 to the z-axis, if i want a real world data?
