### ISSUE TITLE
Inaccurate ground-truth trajectories

### ISSUE THREAD

**Issue by fferflo** [Ford/AVData#37]
I mapped the poses from the `/pose_ground_truth` topic of the first scene (2017-08-04-V2-Log1) onto satellite images of the area  according to the information given in the issues #12 and #29: Map origin is at lat 42.294319 lon -83.223275 and coordinates are given in North,East,Down order in meters. The result is accurate in some parts, but off by several meters in other parts (see e.g. highway-exit at bottom left of the image) while the paper reports cm-accuracy. The error is visible both with bingmaps and googlemaps, so I assume it's not due to an error in the satellite maps. Do you know where this error is coming from?

Bingmaps:
![tf-full](https://user-images.githubusercontent.com/9676570/146672599-8d8710c1-324a-4581-9261-4de8c8fb8e44.png)

Googlemaps:
![googlemaps](https://user-images.githubusercontent.com/9676570/146684075-cc22aae9-d537-40b8-86b0-3e53c9531c5f.png)

**Comment by agarwalsid** [comment]
@fferflo this error is due to the low accuracy of your satellite maps, we have seen that google and bing maps can have meters of error and may not always overlay well with our maps
