### ISSUE TITLE
Relative coordinate system definition

### ISSUE THREAD

**Issue by jingyibo123** [Ford/AVData#6]
Hi everyone,

The topic "pose_ground_truth" and "pose_raw" for each LOG does not start from (0, 0, 0), so what is the definition of the Origin of each sequence?
How is that related to definite location (BLH) of the "gps" topic ?
Thanks for the response.

**Comment by agarwalsid** [comment]
Thank you for pointing that out @jingyibo123, The origin is located at 42.294319, -83.223275 (Lat, Long) and is treated as (0, 0, 0). The map and poses are with respect to this origin. We will add this to out readme page shortly.
